server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: cdn
      authentication-database: admin
      port: 27017

  application:
    name: s-cdn
